name: Fork Sync

on:
  push:
    branches:
      - pj-actions-fork-sync   
#  schedule:
#    - cron: '*/5 * * * *' # every 5 minutes
#  workflow_dispatch: # on button click

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "splunk/public-o11y-docs"
        source_branch: "main"
        destination_branch: "main"
        #github_token: ${{ secrets.PAT }}
